import {
  AcceptTransfer,
  AcceptTransferAs,
  AdminCreateUser,
  AdminCapacity,
  AdminDeleteUser,
  AdminGrantShared,
  AdminListSpaces,
  AdminListUsers,
  AdminRegisterEnabled,
  AdminResetPassword,
  AdminSetPersonalQuota,
  AdminSetRegisterEnabled,
  AdminSetSharedQuota,
  AdminSetUserStatus,
  AdminSharedMembers,
  AppVersion,
  ApplyUpdate,
  CheckUpdate,
  ClearHistory,
  CloudDelete,
  CloudDownload,
  CloudList,
  CloudPreview,
  CloudShare,
  CloudUpload,
  CloudUploadFolder,
  CloudUploadPaths,
  CurrentUser,
  DeleteTask,
  GetLogDirectory,
  GetSettings,
  GetSnapshot,
  KnowledgeAsk,
  KnowledgeHealth,
  KnowledgeLogin,
  KnowledgeLogout,
  KnowledgeStatus,
  Login,
  Logout,
  MySpaces,
  OpenAdminConsole,
  OpenFile,
  OpenReceiveFolder,
  OpenUpdatesFolder,
  PluginInstallFromMarket,
  PluginInstallFromPath,
  PluginInvoke,
  PluginList,
  PluginMarketList,
  PluginSetDisabled,
  PluginUninstall,
  ProcessDroppedFiles,
  RejectTransfer,
  ReportFrontendError,
  SaveSettings,
  SelectFile,
  SelectFiles,
  SelectReceiveDirectory,
  SelectShareDirectory,
  SendBatch,
  SendFile,
  ShutdownAll,
  StartDrive,
  StartUpdateDownload,
  StopDrive,
} from '../../wailsjs/go/main/App'
import type {
  AuthUser,
  Capacity,
  CloudFile,
  CloudPreview as CloudPreviewData,
  CoreSnapshot,
  DroppedFiles,
  KnowledgeAnswer,
  KnowledgeHealth as KnowledgeHealthData,
  KnowledgeStatus as KnowledgeStatusData,
  ManagedUserPage,
  MarketItem,
  PluginInfo,
  PluginInvokeResult,
  Space,
  UpdateCheckResult,
} from '../types/core'

export interface SettingsData {
  deviceName: string
  receiveDir: string
  webdavRoot: string
}

export const core = {
  snapshot: () => GetSnapshot() as Promise<CoreSnapshot>,
  selectFile: SelectFile,
  selectFiles: SelectFiles,
  processDroppedFiles: (paths: string[]) => ProcessDroppedFiles(paths) as Promise<DroppedFiles>,
  send: SendFile,
  sendBatch: SendBatch,
  accept: AcceptTransfer,
  acceptAs: AcceptTransferAs,
  reject: RejectTransfer,
  startDrive: StartDrive,
  stopDrive: StopDrive,
  shutdown: ShutdownAll,
  logDirectory: GetLogDirectory,
  reportError: ReportFrontendError,
  getSettings: () => GetSettings() as Promise<SettingsData>,
  saveSettings: SaveSettings,
  selectReceiveDirectory: SelectReceiveDirectory,
  selectShareDirectory: SelectShareDirectory,
  clearHistory: ClearHistory,
  deleteTask: DeleteTask,
  openFile: OpenFile,
  openReceiveFolder: OpenReceiveFolder,
  cloudList: () => CloudList() as Promise<CloudFile[]>,
  cloudPreview: (key: string) => CloudPreview(key) as Promise<CloudPreviewData>,
  cloudUpload: CloudUpload,
  cloudUploadFolder: CloudUploadFolder,
  cloudUploadPaths: CloudUploadPaths,
  cloudDownload: CloudDownload,
  cloudDelete: CloudDelete,
  cloudShare: CloudShare,
  knowledgeStatus: () => KnowledgeStatus() as Promise<KnowledgeStatusData>,
  knowledgeLogin: (serverUrl: string, username: string, password: string) =>
    KnowledgeLogin(serverUrl, username, password) as Promise<KnowledgeStatusData>,
  knowledgeLogout: KnowledgeLogout,
  knowledgeHealth: () => KnowledgeHealth() as Promise<KnowledgeHealthData>,
  knowledgeAsk: (question: string) => KnowledgeAsk(question) as Promise<KnowledgeAnswer>,
  // 账号控制面（P1）
  login: (username: string, password: string) => Login(username, password) as Promise<AuthUser>,
  logout: Logout,
  currentUser: () => CurrentUser() as Promise<AuthUser>,
  // 管理页（P3）：客户端内自绘，直接调控制面。鉴权在控制面，非管理员一律被拒。
  adminListUsers: (pageNum: number, pageSize: number) =>
    AdminListUsers(pageNum, pageSize) as Promise<ManagedUserPage>,
  adminCreateUser: (userName: string, nickName: string, password: string) =>
    AdminCreateUser({ userName, nickName, password } as never),
  adminSetUserStatus: AdminSetUserStatus,
  adminResetPassword: AdminResetPassword,
  adminDeleteUser: AdminDeleteUser,
  adminRegisterEnabled: () => AdminRegisterEnabled() as Promise<boolean>,
  adminSetRegisterEnabled: AdminSetRegisterEnabled,
  // 空间与配额（P3）：管理页在一处设定共享容量与逐账号个人配额
  mySpaces: () => MySpaces() as Promise<Space[]>,
  adminListSpaces: () => AdminListSpaces() as Promise<Space[]>,
  adminCapacity: () => AdminCapacity() as Promise<Capacity>,
  adminSharedMembers: () => AdminSharedMembers() as Promise<Record<string, string>>,
  adminSetPersonalQuota: AdminSetPersonalQuota,
  adminSetSharedQuota: AdminSetSharedQuota,
  adminGrantShared: AdminGrantShared,
  // RuoYi 自带后台：仅本产品不复刻的运维动作（菜单/字典/定时任务）用得到
  openAdminConsole: OpenAdminConsole,
  // 在线升级（appupdate.go）：检查 → 下载（进度经 update:progress 事件）→ 应用
  appVersion: () => AppVersion() as Promise<string>,
  checkUpdate: () => CheckUpdate() as Promise<UpdateCheckResult>,
  startUpdateDownload: StartUpdateDownload,
  applyUpdate: ApplyUpdate,
  openUpdatesFolder: OpenUpdatesFolder,
  // 插件系统（appplugin.go）：能力调用走动态通道，不随能力增减改绑定
  pluginList: () => PluginList() as Promise<PluginInfo[]>,
  pluginInvoke: (pluginId: string, api: string, args: unknown) =>
    PluginInvoke(pluginId, api, JSON.stringify(args ?? {})) as Promise<PluginInvokeResult>,
  pluginInstallFromPath: (path: string) => PluginInstallFromPath(path) as Promise<PluginInfo>,
  pluginSetDisabled: PluginSetDisabled,
  pluginUninstall: PluginUninstall,
  // 插件商城（RuoYi /easyshare/plugins）：列表已按本地版本回填 updateAvailable
  pluginMarketList: () => PluginMarketList() as Promise<MarketItem[]>,
  pluginInstallFromMarket: (assetId: string, sha256: string, sizeBytes: number) =>
    PluginInstallFromMarket(assetId, sha256, sizeBytes) as Promise<PluginInfo>,
}
