// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {knowledge} from '../models';
import {main} from '../models';
import {http} from '../models';
import {cloud} from '../models';
import {desktop} from '../models';
import {fsutil} from '../models';
import {plugin} from '../models';
import {context} from '../models';

export function AcceptTransfer(arg1:string):Promise<void>;

export function AcceptTransferAs(arg1:string):Promise<void>;

export function AdminCapacity():Promise<account.Capacity>;

export function AdminCreateUser(arg1:account.NewUser):Promise<void>;

export function AdminDeleteUser(arg1:string):Promise<void>;

export function AdminGrantShared(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AdminKnowledgeStats(arg1:number):Promise<knowledge.KnowledgeStats>;

export function AdminListDepts():Promise<Array<main.AdminDept>>;

export function AdminListSpaces():Promise<Array<account.Space>>;

export function AdminListUsers(arg1:number,arg2:number):Promise<account.UserPage>;

export function AdminRegisterEnabled():Promise<boolean>;

export function AdminResetPassword(arg1:string,arg2:string):Promise<void>;

export function AdminSetPersonalQuota(arg1:string,arg2:number):Promise<void>;

export function AdminSetRegisterEnabled(arg1:boolean):Promise<void>;

export function AdminSetSharedQuota(arg1:number):Promise<void>;

export function AdminSetUserStatus(arg1:string,arg2:boolean):Promise<void>;

export function AdminSharedMembers():Promise<Array<main.AdminSharedMember>>;

export function AppVersion():Promise<string>;

export function ApplyUpdate():Promise<void>;

export function AssetHandler():Promise<http.Handler>;

export function CheckUpdate():Promise<main.UpdateCheckResult>;

export function ClearHistory():Promise<void>;

export function CloudDelete(arg1:string):Promise<void>;

export function CloudDownload(arg1:string):Promise<void>;

export function CloudList():Promise<Array<cloud.File>>;

export function CloudPreview(arg1:string):Promise<cloud.Preview>;

export function CloudShare(arg1:string,arg2:number):Promise<string>;

export function CloudUpload(arg1:string):Promise<string>;

export function CloudUploadFolder(arg1:string):Promise<string>;

export function CloudUploadPaths(arg1:Array<string>):Promise<void>;

export function CurrentUser():Promise<main.AuthUser>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetLogDirectory():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetSnapshot():Promise<desktop.Snapshot>;

export function Greet(arg1:string):Promise<string>;

export function KnowledgeAsk(arg1:string):Promise<knowledge.Answer>;

export function KnowledgeHealth():Promise<knowledge.Health>;

export function KnowledgeLogin(arg1:string,arg2:string,arg3:string):Promise<knowledge.StatusView>;

export function KnowledgeLogout():Promise<void>;

export function KnowledgeStatus():Promise<knowledge.StatusView>;

export function ListDir(arg1:string):Promise<Array<fsutil.FileEntry>>;

export function ListDrives():Promise<Array<fsutil.DriveInfo>>;

export function Login(arg1:string,arg2:string):Promise<main.AuthUser>;

export function Logout():Promise<void>;

export function MySpaces():Promise<Array<account.Space>>;

export function OpenAdminConsole():Promise<void>;

export function OpenCurrentSpace():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenReceiveFolder():Promise<void>;

export function OpenUpdatesFolder():Promise<void>;

export function PluginInstallFromMarket(arg1:string,arg2:string,arg3:number,arg4:Array<string>):Promise<plugin.Info>;

export function PluginInstallFromPath(arg1:string):Promise<plugin.Info>;

export function PluginInvoke(arg1:string,arg2:string,arg3:string):Promise<main.PluginInvokeResult>;

export function PluginList():Promise<Array<plugin.Info>>;

export function PluginMarketList():Promise<Array<plugin.MarketItem>>;

export function PluginPreviewFromMarket(arg1:string,arg2:string,arg3:number):Promise<plugin.PreviewResult>;

export function PluginSetDisabled(arg1:string,arg2:boolean):Promise<void>;

export function PluginUninstall(arg1:string):Promise<void>;

export function ProcessDroppedFiles(arg1:Array<string>):Promise<main.FilesDroppedEvent>;

export function RejectTransfer(arg1:string):Promise<void>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectReceiveDirectory():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function SendBatch(arg1:string,arg2:Array<string>):Promise<void>;

export function SendFile(arg1:string,arg2:string):Promise<void>;

export function SetDropSpace(arg1:string):Promise<void>;

export function SetFileVisibility(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function ShutdownAll():Promise<void>;

export function StartDrive():Promise<void>;

export function StartUpdateDownload():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopDrive():Promise<void>;
