// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AcceptTransfer(arg1:string):Promise<void>;

export function GetLogDirectory():Promise<string>;

export function GetSnapshot():Promise<desktop.Snapshot>;

export function Greet(arg1:string):Promise<string>;

export function MapDrive():Promise<void>;

export function RejectTransfer(arg1:string):Promise<void>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function SendFile(arg1:string,arg2:string):Promise<void>;

export function ShutdownAll():Promise<void>;

export function StartDrive():Promise<void>;

export function StopDrive():Promise<void>;

export function UnmapDrive():Promise<void>;
