// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cloud} from '../models';
import {main} from '../models';
import {desktop} from '../models';
import {fsutil} from '../models';
import {context} from '../models';

export function AcceptTransfer(arg1:string):Promise<void>;

export function AcceptTransferAs(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CloudDelete(arg1:string):Promise<void>;

export function CloudDownload(arg1:string):Promise<void>;

export function CloudList():Promise<Array<cloud.File>>;

export function CloudPreview(arg1:string):Promise<cloud.Preview>;

export function CloudShare(arg1:string,arg2:number):Promise<string>;

export function CloudUpload():Promise<string>;

export function CloudUploadFolder():Promise<string>;

export function CloudUploadPaths(arg1:Array<string>):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetLogDirectory():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetSnapshot():Promise<desktop.Snapshot>;

export function Greet(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<fsutil.FileEntry>>;

export function ListDrives():Promise<Array<fsutil.DriveInfo>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenReceiveFolder():Promise<void>;

export function ProcessDroppedFiles(arg1:Array<string>):Promise<main.FilesDroppedEvent>;

export function RejectTransfer(arg1:string):Promise<void>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectReceiveDirectory():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function SendFile(arg1:string,arg2:string):Promise<void>;

export function SendBatch(arg1:string,arg2:Array<string>):Promise<void>;

export function ShutdownAll():Promise<void>;

export function StartDrive():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopDrive():Promise<void>;
