// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1) {
  return window['go']['main']['App']['AcceptTransfer'](arg1);
}

export function AcceptTransferAs(arg1) {
  return window['go']['main']['App']['AcceptTransferAs'](arg1);
}

export function GetLogDirectory() {
  return window['go']['main']['App']['GetLogDirectory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MapDrive() {
  return window['go']['main']['App']['MapDrive']();
}

export function RejectTransfer(arg1) {
  return window['go']['main']['App']['RejectTransfer'](arg1);
}

export function ReportFrontendError(arg1, arg2) {
  return window['go']['main']['App']['ReportFrontendError'](arg1, arg2);
}

export function SaveSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectReceiveDirectory() {
  return window['go']['main']['App']['SelectReceiveDirectory']();
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}

export function ShutdownAll() {
  return window['go']['main']['App']['ShutdownAll']();
}

export function StartDrive() {
  return window['go']['main']['App']['StartDrive']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopDrive() {
  return window['go']['main']['App']['StopDrive']();
}

export function UnmapDrive() {
  return window['go']['main']['App']['UnmapDrive']();
}
