// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1) {
  return window['go']['main']['App']['AcceptTransfer'](arg1);
}

export function AcceptTransferAs(arg1) {
  return window['go']['main']['App']['AcceptTransferAs'](arg1);
}

export function AdminCapacity() {
  return window['go']['main']['App']['AdminCapacity']();
}

export function AdminCreateUser(arg1) {
  return window['go']['main']['App']['AdminCreateUser'](arg1);
}

export function AdminDeleteUser(arg1) {
  return window['go']['main']['App']['AdminDeleteUser'](arg1);
}

export function AdminGrantShared(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminGrantShared'](arg1, arg2, arg3);
}

export function AdminListDepts() {
  return window['go']['main']['App']['AdminListDepts']();
}

export function AdminListSpaces() {
  return window['go']['main']['App']['AdminListSpaces']();
}

export function AdminListUsers(arg1, arg2) {
  return window['go']['main']['App']['AdminListUsers'](arg1, arg2);
}

export function AdminRegisterEnabled() {
  return window['go']['main']['App']['AdminRegisterEnabled']();
}

export function AdminResetPassword(arg1, arg2) {
  return window['go']['main']['App']['AdminResetPassword'](arg1, arg2);
}

export function AdminSetPersonalQuota(arg1, arg2) {
  return window['go']['main']['App']['AdminSetPersonalQuota'](arg1, arg2);
}

export function AdminSetRegisterEnabled(arg1) {
  return window['go']['main']['App']['AdminSetRegisterEnabled'](arg1);
}

export function AdminSetSharedQuota(arg1) {
  return window['go']['main']['App']['AdminSetSharedQuota'](arg1);
}

export function AdminSetUserStatus(arg1, arg2) {
  return window['go']['main']['App']['AdminSetUserStatus'](arg1, arg2);
}

export function AdminSharedMembers() {
  return window['go']['main']['App']['AdminSharedMembers']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function AssetHandler() {
  return window['go']['main']['App']['AssetHandler']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloudDelete(arg1) {
  return window['go']['main']['App']['CloudDelete'](arg1);
}

export function CloudDownload(arg1) {
  return window['go']['main']['App']['CloudDownload'](arg1);
}

export function CloudList() {
  return window['go']['main']['App']['CloudList']();
}

export function CloudPreview(arg1) {
  return window['go']['main']['App']['CloudPreview'](arg1);
}

export function CloudShare(arg1, arg2) {
  return window['go']['main']['App']['CloudShare'](arg1, arg2);
}

export function CloudUpload(arg1) {
  return window['go']['main']['App']['CloudUpload'](arg1);
}

export function CloudUploadFolder(arg1) {
  return window['go']['main']['App']['CloudUploadFolder'](arg1);
}

export function CloudUploadPaths(arg1) {
  return window['go']['main']['App']['CloudUploadPaths'](arg1);
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetLogDirectory() {
  return window['go']['main']['App']['GetLogDirectory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KnowledgeAsk(arg1) {
  return window['go']['main']['App']['KnowledgeAsk'](arg1);
}

export function KnowledgeHealth() {
  return window['go']['main']['App']['KnowledgeHealth']();
}

export function KnowledgeLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['KnowledgeLogin'](arg1, arg2, arg3);
}

export function KnowledgeLogout() {
  return window['go']['main']['App']['KnowledgeLogout']();
}

export function KnowledgeStatus() {
  return window['go']['main']['App']['KnowledgeStatus']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MySpaces() {
  return window['go']['main']['App']['MySpaces']();
}

export function OpenAdminConsole() {
  return window['go']['main']['App']['OpenAdminConsole']();
}

export function OpenCurrentSpace() {
  return window['go']['main']['App']['OpenCurrentSpace']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenReceiveFolder() {
  return window['go']['main']['App']['OpenReceiveFolder']();
}

export function OpenUpdatesFolder() {
  return window['go']['main']['App']['OpenUpdatesFolder']();
}

export function PluginInstallFromMarket(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginInstallFromMarket'](arg1, arg2, arg3, arg4);
}

export function PluginInstallFromPath(arg1) {
  return window['go']['main']['App']['PluginInstallFromPath'](arg1);
}

export function PluginInvoke(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginInvoke'](arg1, arg2, arg3);
}

export function PluginList() {
  return window['go']['main']['App']['PluginList']();
}

export function PluginMarketList() {
  return window['go']['main']['App']['PluginMarketList']();
}

export function PluginPreviewFromMarket(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginPreviewFromMarket'](arg1, arg2, arg3);
}

export function PluginSetDisabled(arg1, arg2) {
  return window['go']['main']['App']['PluginSetDisabled'](arg1, arg2);
}

export function PluginUninstall(arg1) {
  return window['go']['main']['App']['PluginUninstall'](arg1);
}

export function ProcessDroppedFiles(arg1) {
  return window['go']['main']['App']['ProcessDroppedFiles'](arg1);
}

export function RejectTransfer(arg1) {
  return window['go']['main']['App']['RejectTransfer'](arg1);
}

export function ReportFrontendError(arg1, arg2) {
  return window['go']['main']['App']['ReportFrontendError'](arg1, arg2);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectReceiveDirectory() {
  return window['go']['main']['App']['SelectReceiveDirectory']();
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function SendBatch(arg1, arg2) {
  return window['go']['main']['App']['SendBatch'](arg1, arg2);
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}

export function SetDropSpace(arg1) {
  return window['go']['main']['App']['SetDropSpace'](arg1);
}

export function ShutdownAll() {
  return window['go']['main']['App']['ShutdownAll']();
}

export function StartDrive() {
  return window['go']['main']['App']['StartDrive']();
}

export function StartUpdateDownload() {
  return window['go']['main']['App']['StartUpdateDownload']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopDrive() {
  return window['go']['main']['App']['StopDrive']();
}
